name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Dotnet Publish
      uses: EasyDesk/action-dotnet-publish@v1.0.0
      with:
        path: rm-cicd/rm-cicd.csproj
        output-dir: packages
        build-configuration: Release
        skip-build: true
